#pragma once
// App UI language. Diagnostics/logs intentionally stay English so logs remain
// shareable with support; only human-facing UI chrome is translated.
#include <cstring>

namespace Networking
{
enum class AppLanguage { English = 0, ChineseSimplified = 1 };
inline AppLanguage CurrentLanguage = AppLanguage::English;
inline void SetAppLanguage(AppLanguage Language) noexcept { CurrentLanguage = Language; }

inline const char* TranslateToChinese(const char* English)
{
    struct Pair { const char* En; const char* Zh; };
    static const Pair Table[] = {
        {"Setup", "设置"},
        {"YOUR SPACE. YOUR NEXT CHAPTER.", "你的空间，新的篇章。"},
        {"Welcome\nback.", "欢迎\n回来。"},
        {"You're in.", "登录成功。"},
        {"One last step.", "还差一步。"},
        {"Log in to access your content.", "登录以访问你的内容。"},
        {"Your Epic identity is connected.", "你的 Epic 身份已连接。"},
        {"Secure sign-in with your Epic account.", "使用 Epic 账户安全登录。"},
        {"Epic sign-in succeeded. This account has no product user in this Dev deployment. Create a NEW Dev profile only if you do not need to link an existing game identity. Cancel otherwise.", "Epic 登录成功。此账户在此 Dev 部署中没有产品用户。仅在无需关联现有游戏身份时创建新的 Dev 档案，否则请取消。"},
        {"Loading your Epic profile...", "正在加载 Epic 档案..."},
        {"Display name unavailable", "显示名称不可用"},
        {"Epic Auth verified  /  EOS Connect verified", "Epic 验证通过 / EOS 连接通过"},
        {"Country: %s", "国家/地区：%s"},
        {"Language: %s", "语言：%s"},
        {"Not provided by Epic", "Epic 未提供"},
        {"Refresh profile", "刷新档案"},
        {"Log in with Epic    ->", "使用 Epic 登录    ->"},
        {"Waiting for Epic...", "等待 Epic..."},
        {"Create NEW Dev profile & continue", "创建新 Dev 档案并继续"},
        {"Open Epic friends", "打开 Epic 好友"},
        {"Cancel", "取消"},
        {"Disconnect", "断开连接"},
        {"Friends", "好友"},
        {"Refresh friends", "刷新好友"},
        {"Only friends authorized for this app may be listed.", "仅显示已授权此应用的好友。"},
        {"Activity", "动态"},
        {"Copy log", "复制日志"},
        {"Live events. No secrets or tokens.", "实时事件。不含密钥或令牌。"},
        {"Waiting for your consent - no login retry", "等待你的确认——不会重试登录"},
        {"Auth + Connect verified", "验证通过"},
        {"Cancelled", "已取消"},
        {"Not signed in - check the activity log", "未登录——查看动态日志"},
        {"Ready when you are", "随时可以开始"},
        {"*  SDK ready", "* SDK 就绪"},
        {"*  SDK unavailable", "* SDK 不可用"},
        {"Player login is verified separately.", "玩家登录将单独验证。"},
        {"Private credentials. Clear feedback.", "私有凭据。清晰反馈。"},
        {"One-time setup", "初始设置"},
        {"Install EpicOnlineServicesInstaller.exe once, then open Charge.exe (the included Epic launcher). The app can then ask Epic to display its login UI.", "先安装一次 EpicOnlineServicesInstaller.exe，然后打开 Charge.exe（内置的 Epic 启动器）。应用随后会请求 Epic 显示登录界面。"},
        {"Application credential", "应用凭据"},
        {"Not your Epic account password. Use a rotated secret.", "不是你的 Epic 账户密码。请使用已轮换的密钥。"},
        {"EOS client secret", "EOS 客户端密钥"},
        {"Paste secret", "粘贴密钥"},
        {"Remember on this PC (Windows Credential Manager)", "在此电脑上记住（Windows 凭据管理器）"},
        {"Advanced", "高级"},
        {"Optional portable setup: put your private Charge.local.ini next to Charge.exe. It contains readable credentials; never share or upload it. Carry the same data key between PCs.", "可选便携设置：将私有的 Charge.local.ini 放在 Charge.exe 旁边。其中包含可读凭据，切勿分享或上传。在多台电脑之间使用相同的数据密钥。"},
        {"Cloud storage encryption key (64 hex characters)", "云存储加密密钥（64 位十六进制）"},
        {"Saved developer credential", "已保存的开发者凭据"},
        {"Keep Epic's Developer Auth Tool running on localhost:6547.", "保持 Epic 开发者验证工具运行于 localhost:6547。"},
        {"Charge requires Basic Profile, Friends List, Presence and Country permissions. Epic will ask for consent.", "Charge 需要基本档案、好友列表、在线状态和国家/地区权限。Epic 会请求授权。"},
        {"Load friends after login", "登录后加载好友"},
        {"Allow NEW Dev product-user creation", "允许创建新的 Dev 产品用户"},
        {"This allows a real new PUID to be created. Do not use it to bypass identity linking.", "这将创建真实的新 PUID。请勿用它绕过身份关联。"},
        {"Check SDK", "检查 SDK"},
        {"Forget saved credential", "忘记已保存的凭据"},
        {"Apply setup", "应用设置"},
        {"Save & log in", "保存并登录"},
        {"Auto-login on this PC (saved Epic token)", "在此电脑上自动登录（已保存的 Epic 令牌）"},
        {"Auto-login signs you in on startup when credentials are saved.", "保存凭据后，自动登录将在启动时为你登录。"},
        {"App language", "应用语言"},
        {"Forget auto-login", "忘记自动登录"},
        {"Account", "账户"},
        {"Account details", "账户详情"},
        {"Epic account", "Epic 账户"},
        {"Epic friends overlay", "Epic 好友浮窗"},
        {"Your lobby.", "你的大厅。"},
        {"In session.", "对局中。"},
        {"Lobby for voice and readiness. Match session for the actual game.", "大厅用于语音和准备，比赛对局用于实际游戏。"},
        {"Lobby", "大厅"},
        {"Browse", "浏览"},
        {"Settings", "设置"},
        {"History", "历史"},
        {"Offline", "离线"},
        {"Creating", "创建中"},
        {"Waiting", "等待中"},
        {"Preparing", "准备中"},
        {"Starting", "启动中"},
        {"Running", "进行中"},
        {"Ending", "结束中"},
        {"Complete", "已完成"},
        {"Leaving", "离开中"},
        {"Attention", "注意"},
        {"Squad", "队伍"},
        {"%u ready / %u players  -  %u real, %u test", "%u 就绪 / %u 玩家 - %u 真实，%u 测试"},
        {"TEST", "测试"},
        {"PREVIEW", "预览"},
        {"YOU", "你"},
        {"MEMBER", "成员"},
        {"Ready", "就绪"},
        {"Not ready", "未就绪"},
        {"Test ready", "测试就绪"},
        {"Voice", "语音"},
        {"RTC connected", "RTC 已连接"},
        {"RTC not connected", "RTC 未连接"},
        {"Mute mic", "静音麦克风"},
        {"Enable mic", "启用麦克风"},
        {"Mute audio", "静音扬声器"},
        {"Enable audio", "启用扬声器"},
        {"Applying audio change...", "正在应用音频更改..."},
        {"Solo test controls", "单人测试控制"},
        {"Test players", "测试玩家"},
        {"Test players exercise readiness only. No Epic identity, session slot, or voice.", "测试玩家仅用于演练准备流程，没有 Epic 身份、对局席位或语音。"},
        {"HOST", "房主"},
        {"NO LOBBY", "无大厅"},
        {"Copy lobby ID", "复制大厅 ID"},
        {"Leave lobby", "离开大厅"},
        {"Create lobby", "创建大厅"},
        {"Match session", "比赛对局"},
        {"JOINED", "已加入"},
        {"ACTIVE", "进行中"},
        {"NONE", "无"},
        {"Registered: %u", "已注册：%u"},
        {"Running without registration. Fix the EOS Client Policy for full sessions.", "未注册运行。请修复 EOS 客户端策略以启用完整对局。"},
        {"End match", "结束比赛"},
        {"Prepare next match", "准备下一场"},
        {"I'm not ready", "取消准备"},
        {"I'm ready", "我准备好了"},
        {"Start when everyone is ready", "全员就绪时开始"},
        {"Start without registration", "无注册开始"},
        {"Start match", "开始比赛"},
        {"Join match session", "加入比赛对局"},
        {"Leave match session", "离开比赛对局"},
        {"Leaving the lobby always closes the match session first.", "离开大厅前总会先关闭比赛对局。"},
        {"Lobbies", "大厅列表"},
        {"Match sessions", "比赛对局"},
        {"Search lobbies", "搜索大厅"},
        {"Search sessions", "搜索对局"},
        {"Join", "加入"},
        {"Join session", "加入对局"},
        {"Join by ID", "通过 ID 加入"},
        {"Paste lobby ID", "粘贴大厅 ID"},
        {"Join lobby", "加入大厅"},
        {"Filter by ID, bucket, map, mode", "按 ID、Bucket、地图、模式筛选"},
        {"No lobbies match. Only advertised lobbies appear here.", "没有匹配的大厅，只有公开的大厅会出现在这里。"},
        {"No sessions match. New sessions take a few seconds to index.", "没有匹配的对局，新对局需要几秒钟索引。"},
        {"Tags", "标签"},
        {"Style", "类型"},
        {"Ranked", "排位"},
        {"Casual", "休闲"},
        {"Any", "全部"},
        {"Status", "状态"},
        {"Open", "开放"},
        {"In match", "对局中"},
        {"Full", "已满"},
        {"Visibility", "可见性"},
        {"Public", "公开"},
        {"Presence", "在线可见"},
        {"Invite", "仅邀请"},
        {"Language tag", "语言标签"},
        {"e.g. en", "例如 en"},
        {"Lobby settings", "大厅设置"},
        {"Used on Create. Host can apply live.", "创建时使用，房主可实时应用。"},
        {"Max members", "人数上限"},
        {"Permission", "权限"},
        {"Presence enabled", "启用在线状态"},
        {"Allow invites", "允许邀请"},
        {"Enable voice room", "启用语音房"},
        {"Disable host migration", "禁用房主迁移"},
        {"Allow join by ID", "允许通过 ID 加入"},
        {"Rejoin after kick needs invite", "被踢后重进需要邀请"},
        {"Auto-join voice", "自动加入语音"},
        {"Map", "地图"},
        {"Mode", "模式"},
        {"Region", "地区"},
        {"Note", "备注"},
        {"Style (ranked/casual)", "类型（排位/休闲）"},
        {"Language (en/zh/...)", "语言（en/zh/……）"},
        {"Apply lobby settings", "应用大厅设置"},
        {"Create lobby with these settings", "使用这些设置创建大厅"},
        {"Match session settings", "比赛对局设置"},
        {"Used when the host prepares the session.", "房主准备对局时使用。"},
        {"Session name", "对局名称"},
        {"Max players", "玩家上限"},
        {"Allow join in progress", "允许中途加入"},
        {"Apply session settings", "应用对局设置"},
        {"Lobby settings applied.", "大厅设置已应用。"},
        {"Invalid lobby settings. Check bucket and lengths.", "大厅设置无效，请检查 Bucket 和长度。"},
        {"Session settings applied.", "对局设置已应用。"},
        {"Invalid session settings. Check name and bucket.", "对局设置无效，请检查名称和 Bucket。"},
        {"Session name: letters, numbers, - and _. Bucket: letters, numbers, - _ : .", "对局名称：字母、数字、- 和 _。Bucket：字母、数字、- _ : ."},
        {"LAST LOGIN", "上次登录"},
        {"COMPLETED TESTS", "已完成测试"},
        {"LAST MATCH", "上一场"},
        {"Up to 64 records. Client history only.", "最多 64 条记录，仅客户端历史。"},
        {"Sync cloud history", "同步云端历史"},
        {"Activity log", "活动日志"},
        {"Redacted. No secrets or tokens.", "已脱敏，不含密钥或令牌。"},
        {"No record yet", "暂无记录"},
        {"Unavailable", "不可用"},
        {"no map", "无地图"},
        {"voice", "语音"},
        {"EOS LOBBY + MATCH SESSION + RTC  /  Leaving the lobby closes the session first", "EOS 大厅 + 比赛对局 + RTC / 离开大厅前先关闭对局"},
        {"Premium multiplayer (Photon)", "高级多人联机（Photon）"},
        {"Route match traffic over Photon after login. Off stays on EOS only.", "登录后通过 Photon 传输对局流量，关闭则仅使用 EOS。"},
        {"Premium is a manual switch for now. Xsolla will decide it later.", "高级联机目前为手动开关，之后将由 Xsolla 决定。"},
        {"Transport: %s", "传输：%s"},
        {"Photon", "Photon"},
        {"Photon connecting", "Photon 连接中"},
        {"Photon unavailable", "Photon 不可用"},
        {"EOS only", "仅 EOS"},
        {"Starting...", "启动中..."},
    };
    for (const auto& Entry : Table)
        if (std::strcmp(Entry.En, English) == 0) return Entry.Zh;
    return nullptr;
}

inline const char* T(const char* English)
{
    if (!English || CurrentLanguage == AppLanguage::English) return English;
    const char* Translated = TranslateToChinese(English);
    return Translated ? Translated : English;
}

inline const char* PermissionComboItems() noexcept
{
    if (CurrentLanguage == AppLanguage::ChineseSimplified)
        return "公开\0在线可见\0仅邀请\0";
    return "Public advertised\0Join via presence\0Invite only\0";
}

inline const char* LanguageComboItems() noexcept
{
    return "English\0简体中文\0";
}
}
